spring:
  datasource:
    url: jdbc:mysql://database-gachigalle-deploy.cwzy7toscnyc.ap-northeast-2.rds.amazonaws.com:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: gachigalle18
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

config:
  domain: http://gachigallae.s3-website.ap-northeast-2.amazonaws.com

jwt:
  secret-key: ato12345678910fghgjkliygfbfghjhggjytdfdgbcnvjhhgjgyfthato12345678910fghgjkliygfbfghjhggjytdfdgbcnvjhhgjgyfthato12345678910fghgjkliygfbfghjhggjytdfdgbcnvjhhgjgyfthato123456789>
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 20160

mail:
  address:
    admin: admin@email.com

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace